"""Core schema: employer, employee, claim, app_user, user_employer_assignment,
audit_event — plus AD-4 grants and audit_event row-level security.

Grants (re-run safely on every e2e reset):
- lineworker_app: CRUD on domain tables; INSERT + SELECT only on
  audit_event (no UPDATE/DELETE/TRUNCATE)
- audit_redactor: exactly two grants on audit_event — UPDATE (before, after)
  and DELETE constrained by RLS to rows older than the retention floor

Revision ID: 0003_core_schema
Revises: 0002_vector_and_roles
Create Date: 2026-08-10

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from config import get_settings

revision: str = "0003_core_schema"
down_revision: str | None = "0002_vector_and_roles"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "role", sa.Enum("handler", "supervisor", "analyst", name="user_role"), nullable=False
        ),
        sa.Column("scope_all", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("name", "role", name=op.f("uq_app_user_name")),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("employee_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("gender", sa.Enum("female", "male", "other", name="gender"), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("dept", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee")),
        sa.UniqueConstraint("employee_id", name=op.f("uq_employee_employee_id")),
    )
    op.create_table(
        "employer",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employer")),
        sa.UniqueConstraint("name", name=op.f("uq_employer_name")),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column(
            "actor_role",
            sa.Enum("handler", "supervisor", "analyst", name="user_role"),
            nullable=False,
        ),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["app_user.id"], name=op.f("fk_audit_event_actor_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_table(
        "claim",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("policy_num", sa.Text(), nullable=False),
        sa.Column("employer_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("handler_id", sa.Integer(), nullable=False),
        sa.Column("plant", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("doi", sa.Date(), nullable=False),
        sa.Column("froi_date", sa.Date(), nullable=False),
        sa.Column("assign_date", sa.Date(), nullable=False),
        sa.Column("approval_date", sa.Date(), nullable=True),
        sa.Column("rtw_rec", sa.Date(), nullable=True),
        sa.Column("actual_rtw", sa.Date(), nullable=True),
        sa.Column("injury_type", sa.Text(), nullable=False),
        sa.Column("cause", sa.Text(), nullable=False),
        sa.Column("body_part", sa.Text(), nullable=False),
        sa.Column("body_key", sa.Text(), nullable=False),
        sa.Column("icd", sa.Text(), nullable=False),
        sa.Column("icd_desc", sa.Text(), nullable=False),
        sa.Column("severity_score", sa.Integer(), nullable=False),
        sa.Column(
            "disability", sa.Enum("temporary", "permanent", name="disability"), nullable=False
        ),
        sa.Column("recovery", sa.Text(), nullable=False),
        sa.Column("surgery_required", sa.Boolean(), nullable=False),
        sa.Column("contraindications", sa.Text(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("intake", "investigation", "treatment", "settled", name="stage"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "initial",
                "ch_assessment_process",
                "ch_approved",
                "denied",
                "settled",
                "settled_closed",
                name="claim_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "comm_status",
            sa.Enum(
                "fnol_received",
                "incomplete_information",
                "need_for_additional_information",
                "documents_received_and_approved",
                "initial_approval_provided_treatment_underway",
                name="comm_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "return_status",
            sa.Enum(
                "under_treatment",
                "returned_and_under_therapy",
                "returned_and_fully_recovered",
                name="return_status",
            ),
            nullable=False,
        ),
        sa.Column("osha_recordable", sa.Boolean(), nullable=False),
        sa.Column("litigation_flag", sa.Boolean(), nullable=False),
        sa.Column("attorney_rep", sa.Boolean(), nullable=False),
        sa.Column("fraud_score", sa.Integer(), nullable=False),
        sa.Column("fraud_flag", sa.Boolean(), nullable=False),
        sa.Column("paid_indemnity", sa.BigInteger(), nullable=False),
        sa.Column("paid_medical", sa.BigInteger(), nullable=False),
        sa.Column("paid_expense", sa.BigInteger(), nullable=False),
        sa.Column("reserve", sa.BigInteger(), nullable=False),
        sa.Column("aww", sa.BigInteger(), nullable=False),
        sa.Column("days_recovery", sa.Integer(), nullable=True),
        sa.Column("settlement_days", sa.Integer(), nullable=True),
        sa.Column("sla_pick_days", sa.Integer(), nullable=True),
        sa.Column("sla_approve_days", sa.Integer(), nullable=True),
        sa.Column("sla_settle_days", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employee.id"], name=op.f("fk_claim_employee_id_employee")
        ),
        sa.ForeignKeyConstraint(
            ["employer_id"], ["employer.id"], name=op.f("fk_claim_employer_id_employer")
        ),
        sa.ForeignKeyConstraint(
            ["handler_id"], ["app_user.id"], name=op.f("fk_claim_handler_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim")),
        sa.UniqueConstraint("claim_id", name=op.f("uq_claim_claim_id")),
    )
    op.create_table(
        "user_employer_assignment",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("employer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employer_id"],
            ["employer.id"],
            name=op.f("fk_user_employer_assignment_employer_id_employer"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_user_employer_assignment_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_employer_assignment")),
        sa.UniqueConstraint(
            "user_id", "employer_id", name=op.f("uq_user_employer_assignment_user_id")
        ),
    )
    # ### end Alembic commands ###

    # --- Grants (AD-4 grant surface) -------------------------------------
    retention_years = int(get_settings().audit_retention_years)
    op.execute("GRANT USAGE ON SCHEMA public TO lineworker_app, audit_redactor")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON "
        "employer, employee, claim, app_user, user_employer_assignment TO lineworker_app"
    )
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lineworker_app")
    # App role is INSERT-only on the audit log (reads allowed; never
    # UPDATE/DELETE/TRUNCATE — append-only is DB-enforced).
    op.execute("GRANT SELECT, INSERT ON audit_event TO lineworker_app")
    # audit_redactor: three grants on audit_event, nothing else. SELECT is
    # required for the other two to be usable at all — Postgres demands
    # SELECT on every column named in a WHERE clause, so without it the only
    # executable redaction is the unqualified one that rewrites every row.
    # RLS below still bounds which rows it can reach.
    op.execute("GRANT SELECT ON audit_event TO audit_redactor")
    op.execute('GRANT UPDATE ("before", "after") ON audit_event TO audit_redactor')
    op.execute("GRANT DELETE ON audit_event TO audit_redactor")

    # --- Row-level security on audit_event -------------------------------
    op.execute("ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY audit_app_insert ON audit_event FOR INSERT TO lineworker_app "
        "WITH CHECK (true)"
    )
    op.execute(
        "CREATE POLICY audit_app_select ON audit_event FOR SELECT TO lineworker_app USING (true)"
    )
    # Postgres applies SELECT policies to the rows an UPDATE/DELETE reads
    # through its WHERE clause, so without this policy a targeted redaction
    # does not error — it silently matches zero rows. Scoped to match the
    # update policy: the role can already rewrite any row, so making those
    # same rows visible to it grants no new reach.
    op.execute(
        "CREATE POLICY audit_redactor_select ON audit_event FOR SELECT TO audit_redactor "
        "USING (true)"
    )
    op.execute(
        "CREATE POLICY audit_redactor_update ON audit_event FOR UPDATE TO audit_redactor "
        "USING (true)"
    )
    op.execute(
        "CREATE POLICY audit_redactor_delete ON audit_event FOR DELETE TO audit_redactor "
        f"USING (at < now() - interval '{retention_years} years')"
    )


def downgrade() -> None:
    # Policies and grants drop with their tables.
    op.drop_table("user_employer_assignment")
    op.drop_table("claim")
    op.drop_table("audit_event")
    op.drop_table("employer")
    op.drop_table("employee")
    op.drop_table("app_user")
    for enum_name in (
        "claim_status",
        "comm_status",
        "return_status",
        "stage",
        "disability",
        "gender",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
