"""Deterministic `ChatClient`s for tests, and why the suite has them.

`agents/client.py` defines `ChatClient` as a `Protocol` precisely so that
everything above it — the AD-2 figure equality, the schema-rejection path, the
low-risk fraud variant, the upsert semantics, the scope refusals, the injection
fixtures — can be asserted without a model server, a GPU, a container or a
network. These are those fakes, and `tests/embedding_fixture.py` is the same
idea one story earlier.

**What they answer is filler, and it says so.** No test in this suite asserts on
a generated sentence: the narrative is model output and AD-15's rule about
asserting structure rather than prose holds at the unit level too. What the
fakes have to be is *valid* — a schema-conformant answer, so the persistence
path under test is the one that runs when a model behaves — and *deterministic*,
so a failure is a failure rather than a coin toss.

**`FakeChatClient` fills a schema by walking its fields**, which is a stronger
fixture than four hand-written narratives for a reason worth stating: it can
only work while every narrative field is a string or a list of strings, which is
exactly the AD-2 property `test_ai_insights.py` asserts structurally. A story
that added a `reserve_cents: int` to a narrative schema would break this fake
loudly, in every insight test at once, rather than quietly acquiring a figure
the model originates.
"""

from typing import Any, get_args, get_origin

from pydantic import BaseModel

from agents.client import ChatSchemaRejected, ChatUnavailable

#: Long enough to clear the shared prose bounds in `agents/schemas.py` without
#: importing them — a fake that satisfied the constraints by reading them could
#: not notice a constraint that had been quietly relaxed.
_SENTENCE = "Deterministic test narrative, generated by a fake chat client and not by any model."
_CLAUSE = "Deterministic test clause from the fake chat client."


class FakeChatClient:
    """A `ChatClient` with no I/O. Records every prompt it was given.

    `calls` holds one `(system, user, schema)` triple per completion, which is
    what the AD-16 injection fixtures assert against: they need to see the
    *composed* system message and the *fenced* user message, and neither exists
    anywhere else — the whole point of the design is that the prompt is built
    and sent without being stored.

    `model` is present because `services/rag/insights.py` reads it off the
    client to write `ai_insight.model`. A fake that omitted it would leave the
    provenance column untested, and the card labels the narrative with it.
    """

    model = "fake-chat"

    def __init__(self) -> None:
        self.calls: list[tuple[str, str, type[BaseModel]]] = []

    async def structured[T: BaseModel](self, *, system: str, user: str, schema: type[T]) -> T:
        self.calls.append((system, user, schema))
        return fill(schema)

    @property
    def prompts(self) -> list[str]:
        """Every message body this client was handed, system and user alike."""
        return [part for system, user, _schema in self.calls for part in (system, user)]


class UnavailableChatClient:
    """A `ChatClient` that is always down — the degradation path.

    Raises `ChatUnavailable`, which is what the shipped client raises for a
    transport failure, so the assertion is about the code path rather than about
    a particular vendor exception. The distinction from `MalformedChatClient`
    below is the whole reason both exist: one produces a 503 on the interactive
    route and the other a 200 with the previous cards standing.
    """

    model = "unavailable-chat"

    def __init__(self) -> None:
        self.calls = 0

    async def structured[T: BaseModel](self, *, system: str, user: str, schema: type[T]) -> T:
        self.calls += 1
        raise ChatUnavailable("no model server")


class MalformedChatClient:
    """A `ChatClient` whose answer fails the schema — for one kind, or for all.

    `reject` names the narrative schemas to refuse; anything else is answered
    normally. That asymmetry is the point of the fixture: the I/O matrix says a
    malformed answer for one kind must leave the other three persisted, and a
    fake that failed everything could not tell that outcome from a total
    failure.

    Raises `ChatSchemaRejected` because that is what the shipped client raises
    when `PydanticOutputParser` refuses a completion. Returning an invalid
    object instead is not possible from a typed method, and would in any case be
    testing Pydantic rather than this codebase.
    """

    model = "malformed-chat"

    def __init__(self, *reject: type[BaseModel]) -> None:
        self._reject = set(reject)
        self.calls: list[type[BaseModel]] = []

    async def structured[T: BaseModel](self, *, system: str, user: str, schema: type[T]) -> T:
        self.calls.append(schema)
        if not self._reject or schema in self._reject:
            raise ChatSchemaRejected(f"bad answer for {schema.__name__}")
        return fill(schema)


def fill[T: BaseModel](schema: type[T]) -> T:
    """A valid instance of a narrative schema, built by walking its fields.

    Handles exactly two annotations — `str` and `list[str]` — and raises for
    anything else, which is the guard rather than a limitation: every field of
    every `*Narrative` in `agents/schemas.py` is prose or a list of prose,
    because a narrative with a numeric field would be a place a model could
    originate a figure (AD-2). A schema that grew one fails here, in every
    insight test at once, with the field named.
    """
    values: dict[str, Any] = {}
    for name, field in schema.model_fields.items():
        annotation = field.annotation
        if annotation is str:
            values[name] = _SENTENCE
        elif get_origin(annotation) is list and get_args(annotation) == (str,):
            values[name] = [_CLAUSE]
        else:
            raise TypeError(
                f"{schema.__name__}.{name} is annotated {annotation!r}; a narrative schema "
                "may only carry prose (str or list[str]) — see agents/schemas.py on AD-2"
            )
    return schema.model_validate(values)


__all__ = ["FakeChatClient", "MalformedChatClient", "UnavailableChatClient", "fill"]
