/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session as a persona */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session server-side
         * @description Idempotent by design: ending a session never requires a valid one.
         *
         *     Requiring authentication here would 401 exactly the caller who most
         *     needs the cookie cleared — one holding an expired or already-revoked
         *     token — and leave that dead cookie in their browser until it aged out.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claims/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The session persona's claim queue, grouped by stage and ranked
         * @description The caller's queue. Filter and page it; you cannot re-scope it.
         */
        get: operations["queue_claims_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every WC glossary term, in display order
         * @description Deliberately without `Cache-Control: no-store`.
         *
         *     `/me` and `/stats/*` set it because their payloads are specific to one
         *     persona's identity or scope, and a cache upstream serving one
         *     supervisor's caseload to another would be a scope leak. Nothing about
         *     this response is caller-specific: every authenticated session gets
         *     byte-identical bytes, there is no PHI in them, and the worst a shared
         *     cache could do is serve the industry's definition of "FNOL" to someone
         *     who had not logged in. Marking it `no-store` anyway would say the
         *     payload was sensitive, which is a claim the next reader would have to
         *     disprove.
         */
        get: operations["glossary_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current persona */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personas available to log in as */
        get: operations["personas_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SLA strip for the session's persona
         * @description The strip, for whoever holds the session cookie — and no one else.
         *
         *     Parameter-free for the same reason `/stats/topbar` is, and with no role
         *     branch of any kind: FR-SLA-1 is the statement that a supervisor,
         *     analyst and handler all get *their* caseload's strip from one
         *     computation, so a branch here would be the defect rather than a
         *     feature.
         */
        get: operations["sla_stats_sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/topbar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caseload tiles for the session's persona */
        get: operations["topbar_stats_topbar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClaimCardResponse
         * @description One queue card — every field of it computed server-side (AD-1).
         *
         *     The four rows the prototype draws, in payload form: identity and age;
         *     risk dot, worker and flag badges; injury type; stage pill and employer.
         *     Nothing here is a hint the client finishes computing — `risk` is a band,
         *     not a score, and `priorityMarker` is a decision, not a rank the SPA
         *     thresholds itself.
         *
         *     `injuryType` carries the **full** string. The prototype clamps it to 30
         *     characters, but the longest in the seeded portfolio is 29, so the clamp
         *     never fires — and truncation is a property of the column it is drawn in,
         *     not of the claim. The card truncates visually and keeps the whole text
         *     available to a screen reader.
         *
         *     `priorityScore` is published deliberately, though the items already
         *     arrive in order. It is what makes the ordering explainable — to a
         *     handler asking why a claim is third, to a spec asserting the rule, and
         *     to Epic 5 reusing the same figure on the dashboard. It is not an
         *     invitation to re-sort: the score depends on a rules version the client
         *     does not have.
         */
        ClaimCardResponse: {
            /** Claimid */
            claimId: string;
            /** Daysopen */
            daysOpen: number;
            /** Employershortname */
            employerShortName: string;
            /** Fraudflag */
            fraudFlag: boolean;
            /** Injurytype */
            injuryType: string;
            /** Litigationflag */
            litigationFlag: boolean;
            /** Paymentdue */
            paymentDue: boolean;
            /** Prioritymarker */
            priorityMarker: boolean;
            /** Priorityscore */
            priorityScore: number;
            risk: components["schemas"]["RiskBand"];
            /** Rtwblocked */
            rtwBlocked: boolean;
            /** Siureview */
            siuReview: boolean;
            stage: components["schemas"]["Stage"];
            /** Workername */
            workerName: string;
        };
        /**
         * ClaimQueueResponse
         * @description The queue, the rules that ranked it, and the two totals behind it.
         *
         *     **Both rule-document versions, not one.** `rulesVersion` names the
         *     `priority_weights` version and `thresholdsVersion` names the
         *     `derivation_thresholds` one. Reporting only the first was reporting half
         *     the answer: the thresholds decide `risk`, `siuReview` and `rtwBlocked`,
         *     which are *inputs* to every score in the payload, and the cursor already
         *     records both for exactly that reason. Any conversation about "why is
         *     this claim first" starts by establishing which documents answered.
         *
         *     **Both totals, and the SPA computes neither.** `unfilteredTotal` is how
         *     many claims the caller has in scope *before* the filter; `filteredTotal`
         *     is how many survived it. The second is the sum of the four group totals,
         *     and it is sent anyway: a client that adds them up has re-implemented
         *     "how big is this queue" in the browser, which is the derivation AD-1
         *     keeps server-side and `noDerivation.test.ts` fails a build over. The pair
         *     is what lets the pane tell "no claims in your caseload" from "no claims
         *     match this filter" (NFR-3) without holding an unfiltered copy of the
         *     caseload to compare against.
         */
        ClaimQueueResponse: {
            /** Filteredtotal */
            filteredTotal: number;
            groups: components["schemas"]["StageGroupsResponse"];
            /** Rulesversion */
            rulesVersion: number;
            /** Thresholdsversion */
            thresholdsVersion: number;
            /** Unfilteredtotal */
            unfilteredTotal: number;
        };
        /**
         * GlossaryList
         * @description The `{items, nextCursor, total}` envelope (Lists convention).
         *
         *     `nextCursor` is structurally always null: the glossary is one fixed
         *     page. The envelope is here so the generated client sees one list shape
         *     across the whole API, the same reasoning `PersonaList` records.
         */
        GlossaryList: {
            /** Items */
            items: components["schemas"]["GlossaryTermResponse"][];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * GlossaryTermResponse
         * @description One term. No `id` and no `sortOrder` on the wire.
         *
         *     Order is carried by the array — the SPA renders the list as given — and
         *     a surrogate key nothing links to would be an invitation to link to it,
         *     which is exactly the `glossary_term`↔`claim` join this story is not
         *     building.
         */
        GlossaryTermResponse: {
            /** Abbreviation */
            abbreviation: string;
            /** Definition */
            definition: string;
            /** Term */
            term: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Personaid */
            personaId: number;
        };
        /** Me */
        Me: {
            /** Id */
            id: number;
            /** Initials */
            initials: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /** Persona */
        Persona: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * PersonaList
         * @description The `{items, nextCursor, total?}` envelope (Lists convention).
         *
         *     The persona list is a fixed ten rows, so `nextCursor` is structurally
         *     always null — the envelope is here so the generated client sees one
         *     list shape across the whole API, not because this list will ever page.
         */
        PersonaList: {
            /** Items */
            items: components["schemas"]["Persona"][];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * QueueFilter
         * @description The eight operational filters (FR-Q-1), snake_case per the enum
         *     convention — "High risk" and "Payment due" are the UI's labels, not the
         *     wire's.
         *
         *     `active` rather than `treatment`: the prototype's option reads "Active /
         *     In treatment", and the filter's meaning is "work in progress". It
         *     happens to be the treatment stage today; naming it after the stage would
         *     freeze that coincidence into the contract.
         * @enum {string}
         */
        QueueFilter: "all" | "active" | "high_risk" | "fraud" | "litigation" | "payment_due" | "surgery" | "siu";
        /**
         * RiskBand
         * @description Snake/lowercase values per the enum convention — the UI owns labels.
         * @enum {string}
         */
        RiskBand: "high" | "med" | "low";
        /**
         * SlaDirection
         * @description Which side of the target is good.
         *
         *     Reported alongside the target because the UI writes the comparison out
         *     (`✓ <1d`, `⚠ >5d`, `✓ >80%`): deriving the operator client-side would
         *     put half of each rule in the browser, where nothing checks it.
         * @enum {string}
         */
        SlaDirection: "below" | "above";
        /**
         * SlaMetricResponse
         * @description One SLA tile, decided entirely server-side (AD-1).
         *
         *     `value` is `null` exactly when `status` is `no_data` — a segment with
         *     no qualifying claims. The SPA renders that as an em dash; what it must
         *     never do is substitute a number, which is the prototype behaviour this
         *     story exists to remove.
         *
         *     `target`, `direction` and `decimals` travel with the value so the UI
         *     can write the comparison out (`✓ <1d`, `⚠ >5d`) and format the figure
         *     without holding an operator, a threshold or a precision of its own.
         */
        SlaMetricResponse: {
            /** Decimals */
            decimals: number;
            direction: components["schemas"]["SlaDirection"];
            status: components["schemas"]["SlaStatus"];
            /** Target */
            target: number;
            /** Value */
            value: number | null;
        };
        /**
         * SlaStatus
         * @description The server's verdict. `no_data` is a first-class answer, not an error.
         *
         *     (`passing` rather than `pass`, which is a Python keyword — the wire
         *     value is `pass`, which is what the contract and the UI see.)
         * @enum {string}
         */
        SlaStatus: "pass" | "warn" | "no_data";
        /**
         * SlaStripResponse
         * @description `{pick, approve, settle, rtwRate}` — camelCase via `ApiModel`.
         */
        SlaStripResponse: {
            approve: components["schemas"]["SlaMetricResponse"];
            pick: components["schemas"]["SlaMetricResponse"];
            rtwRate: components["schemas"]["SlaMetricResponse"];
            settle: components["schemas"]["SlaMetricResponse"];
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "intake" | "investigation" | "treatment" | "settled";
        /**
         * StageGroupResponse
         * @description One stage's page, in the `{items, nextCursor, total}` envelope.
         *
         *     Unlike `/personas` and `/glossary`, whose cursors are structurally null,
         *     this one is real: `total` is the size of the whole filtered group (the
         *     number in the chip beside the stage header) and `nextCursor` is non-null
         *     exactly while claims remain beyond `items`.
         */
        StageGroupResponse: {
            /** Items */
            items: components["schemas"]["ClaimCardResponse"][];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * StageGroupsResponse
         * @description The four groups, always all four.
         *
         *     Named fields rather than a map keyed by stage: the four stages are the
         *     contract (the SPA renders four sections in this order whatever the data
         *     says), and a map would let a response omit one — which the client would
         *     have to render as either "empty" or "unknown", two very different
         *     things.
         */
        StageGroupsResponse: {
            intake: components["schemas"]["StageGroupResponse"];
            investigation: components["schemas"]["StageGroupResponse"];
            settled: components["schemas"]["StageGroupResponse"];
            treatment: components["schemas"]["StageGroupResponse"];
        };
        /**
         * TopBarStatsResponse
         * @description `{caseload, activeTx, highRisk}` — camelCase via `ApiModel`.
         */
        TopBarStatsResponse: {
            /** Activetx */
            activeTx: number;
            /** Caseload */
            caseload: number;
            /** Highrisk */
            highRisk: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "handler" | "supervisor" | "analyst";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queue_claims_queue_get: {
        parameters: {
            query?: {
                /** @description One of the eight operational filters; unknown values are refused. */
                filter?: components["schemas"]["QueueFilter"];
                /** @description Which group `cursor` addresses. Never narrows the response. */
                stage?: components["schemas"]["Stage"] | null;
                /** @description An opaque `nextCursor` from a previous response. */
                cursor?: string | null;
                /** @description Page size per group; defaults to the rules document's. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimQueueResponse"];
                };
            };
            /** @description The pagination cursor is unreadable, or belongs to a different filter, group or rules version (RFC 9457 problem document). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    glossary_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlossaryList"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    personas_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaList"];
                };
            };
        };
    };
    sla_stats_sla_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaStripResponse"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    topbar_stats_topbar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopBarStatsResponse"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
}
