/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a session as a persona */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session server-side
         * @description Idempotent by design: ending a session never requires a valid one.
         *
         *     Requiring authentication here would 401 exactly the caller who most
         *     needs the cookie cleared — one holding an expired or already-revoked
         *     token — and leave that dead cookie in their browser until it aged out.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current persona */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personas available to log in as */
        get: operations["personas_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SLA strip for the session's persona
         * @description The strip, for whoever holds the session cookie — and no one else.
         *
         *     Parameter-free for the same reason `/stats/topbar` is, and with no role
         *     branch of any kind: FR-SLA-1 is the statement that a supervisor,
         *     analyst and handler all get *their* caseload's strip from one
         *     computation, so a branch here would be the defect rather than a
         *     feature.
         */
        get: operations["sla_stats_sla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/topbar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caseload tiles for the session's persona */
        get: operations["topbar_stats_topbar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Personaid */
            personaId: number;
        };
        /** Me */
        Me: {
            /** Id */
            id: number;
            /** Initials */
            initials: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /** Persona */
        Persona: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * PersonaList
         * @description The `{items, nextCursor, total?}` envelope (Lists convention).
         *
         *     The persona list is a fixed ten rows, so `nextCursor` is structurally
         *     always null — the envelope is here so the generated client sees one
         *     list shape across the whole API, not because this list will ever page.
         */
        PersonaList: {
            /** Items */
            items: components["schemas"]["Persona"][];
            /** Nextcursor */
            nextCursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * SlaDirection
         * @description Which side of the target is good.
         *
         *     Reported alongside the target because the UI writes the comparison out
         *     (`✓ <1d`, `⚠ >5d`, `✓ >80%`): deriving the operator client-side would
         *     put half of each rule in the browser, where nothing checks it.
         * @enum {string}
         */
        SlaDirection: "below" | "above";
        /**
         * SlaMetricResponse
         * @description One SLA tile, decided entirely server-side (AD-1).
         *
         *     `value` is `null` exactly when `status` is `no_data` — a segment with
         *     no qualifying claims. The SPA renders that as an em dash; what it must
         *     never do is substitute a number, which is the prototype behaviour this
         *     story exists to remove.
         *
         *     `target`, `direction` and `decimals` travel with the value so the UI
         *     can write the comparison out (`✓ <1d`, `⚠ >5d`) and format the figure
         *     without holding an operator, a threshold or a precision of its own.
         */
        SlaMetricResponse: {
            /** Decimals */
            decimals: number;
            direction: components["schemas"]["SlaDirection"];
            status: components["schemas"]["SlaStatus"];
            /** Target */
            target: number;
            /** Value */
            value: number | null;
        };
        /**
         * SlaStatus
         * @description The server's verdict. `no_data` is a first-class answer, not an error.
         *
         *     (`passing` rather than `pass`, which is a Python keyword — the wire
         *     value is `pass`, which is what the contract and the UI see.)
         * @enum {string}
         */
        SlaStatus: "pass" | "warn" | "no_data";
        /**
         * SlaStripResponse
         * @description `{pick, approve, settle, rtwRate}` — camelCase via `ApiModel`.
         */
        SlaStripResponse: {
            approve: components["schemas"]["SlaMetricResponse"];
            pick: components["schemas"]["SlaMetricResponse"];
            rtwRate: components["schemas"]["SlaMetricResponse"];
            settle: components["schemas"]["SlaMetricResponse"];
        };
        /**
         * TopBarStatsResponse
         * @description `{caseload, activeTx, highRisk}` — camelCase via `ApiModel`.
         */
        TopBarStatsResponse: {
            /** Activetx */
            activeTx: number;
            /** Caseload */
            caseload: number;
            /** Highrisk */
            highRisk: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "handler" | "supervisor" | "analyst";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    personas_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaList"];
                };
            };
        };
    };
    sla_stats_sla_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlaStripResponse"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
    topbar_stats_topbar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopBarStatsResponse"];
                };
            };
            /** @description No valid session (RFC 9457 problem document). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /** Detail */
                        detail: string;
                        /** Status */
                        status: number;
                        /** Title */
                        title: string;
                        /** Type */
                        type: string;
                    };
                };
            };
        };
    };
}
